package edu.sbucse416.electiondata.enums;

public enum ErrorType {
    ENCLOSED_PRECINCT,
    OVERLAPPING_PRECINCT,
    GHOST_PRECINCT,
    PRECINCT_GAP,
    MULTIPOLYGON_PRECINCT,
    ANOMALOUS_DATA_PRECINCT,
    ANOMALOUS_ELECTION_DATA,
    ANOMALOUS_DEMOGRAPHIC_DATA;
}
